apiVersion: v1
kind: ConfigMap
metadata:
  name: photovault-api-config
  namespace: webapps
data:
  PORT: "3001"
  NODE_ENV: "production"
  API_PREFIX: "/api/v1"
  # AVIF Converter Services
  AVIF_CONVERTER_URL: "http://avif-converter-service.webapps.svc.cluster.local:3000"
  AVIF_CONVERTER_TIMEOUT: "300000"
