apiVersion: v1
kind: ConfigMap
metadata:
  name: photovault-api-config
  namespace: photovault
data:
  PORT: "3001"
  NODE_ENV: "production"
  DEBUG: "photovault:*,-express:*,-nodemon:*,-express-router:*"
  API_PREFIX: "/api/v1"
  # AVIF Converter Services
  AVIF_CONVERTER_URL: "http://avif-converter-service.photovault.svc.cluster.local"
  AVIF_CONVERTER_TIMEOUT: "300000"
