apiVersion: apps/v1
kind: Deployment
metadata:
  name: photovault-api
  namespace: webapps
  labels:
    app: photovault-api
  # Updated to disable all health probes for crash debugging - deploy now
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photovault-api
  template:
    metadata:
      labels:
        app: photovault-api
    spec:
      containers:
      - name: photovault-api
        image: ghcr.io/ekskog/photovault-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
        envFrom:
        - configMapRef:
            name: photovault-api-config
        - secretRef:
            name: photovault-api-secret
        volumeMounts:
        - name: log-storage
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 1800  # 30 minutes
          periodSeconds: 60
          timeoutSeconds: 1800  # 30 minutes
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 1800  # 30 minutes
          periodSeconds: 30
          timeoutSeconds: 1800  # 30 minutes
          failureThreshold: 1
        # All probes completely disabled to prevent restart on crash
        # even though copilot can't get this to work at all
        # Updated to trigger manifest redeployment
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"  # Increased for debugging
            cpu: "1000m"     # Increased for debugging
      volumes:
      - name: log-storage
        emptyDir: {}  # Ephemeral storage for logs in Kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: photovault-api-service
  namespace: webapps
  labels:
    app: photovault-api
spec:
  selector:
    app: photovault-api
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  type: LoadBalancer
