apiVersion: v1
kind: Secret
metadata:
  name: photovault-api-secret
  namespace: photovault
type: Opaque
stringData:
  # MinIO Configuration
  MINIO_ENDPOINT: "192.168.1.8"
  MINIO_PORT: "9000"
  MINIO_ACCESS_KEY: "lucarv"
  MINIO_SECRET_KEY: "lucaPWD4MinI0-MJR"
  MINIO_USE_SSL: "false"
  MINIO_BUCKET_NAME: "photovault"

  # MAPDATA
  MAPBOX_TOKEN: "pk.eyJ1IjoiZWtza29nIiwiYSI6ImNtOGswdWd3bTBzdG0ybHNhZnk1cXNvOTYifQ.7XjeS_rurj2R6K6O6rdyxg"
  
  # Authentication Configuration
  AUTH_MODE: "demo"  # Change to "database" for production
  JWT_SECRET: "i was still lookig from afar, aloof; from the hill where god lives"
  JWT_EXPIRES_IN: "24h"

  # Turnstile
  TURNSTILE_SECRET_KEY: 0x4AAAAAABxuiYNCMdVt7lX6AMtT2RfGd1A

  # Database Configuration (for production AUTH_MODE=database)
  DB_HOST: "mariadb-service.data.svc.cluster.local"
  DB_PORT: "3306"
  DB_USER: "root"
  DB_PASSWORD: "rootPWD4mariaDB"
  DB_NAME: "photovault"
