name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: ghcr.io/ekskog/photovault-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for source code changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            source:
              - src/**
              - package.json
              - package-lock.json
              - Dockerfile
              - .dockerignore

      - name: Set Environment Variables
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ env.IMAGE_NAME }}:$SHORT_SHA" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        if: steps.changes.outputs.source == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.EK_GITHUB_PAT }}

      - name: Build and Push Docker Image
        if: steps.changes.outputs.source == 'true'
        run: |
          echo "Building and pushing image: $IMAGE_TAG"
          docker buildx build --platform linux/amd64 -t $IMAGE_TAG --push .
      
      - name: Skip Build (No Source Changes)
        if: steps.changes.outputs.source != 'true'
        run: |
          echo "No source code changes detected. Skipping Docker build."
          echo "Using existing image tag for deployment: $IMAGE_TAG"
      
      - name: Set Up KUBECONFIG
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          echo "KUBECONFIG set to $KUBECONFIG"
                    
      - name: Deploy to Kubernetes
        run: |
          echo "Deploying image: $IMAGE_TAG"
          
          # Delete existing job if it exists (jobs don't update like deployments)
          kubectl delete job photovault-api --namespace=webapps --kubeconfig=$PWD/kubeconfig.yaml --ignore-not-found=true
          
          # Update the job manifest with new image and apply it
          sed "s|ghcr.io/ekskog/photovault-api:latest|$IMAGE_TAG|g" k8s/deployment.yaml | kubectl apply -f - --kubeconfig=$PWD/kubeconfig.yaml
          
          # Add debugging information
          echo "Checking job status..."
          kubectl get jobs photovault-api --namespace=webapps --kubeconfig=$PWD/kubeconfig.yaml
          
          echo "Checking pod status..."
          kubectl get pods -l app=photovault-api --namespace=webapps --kubeconfig=$PWD/kubeconfig.yaml
          
          echo "Checking recent events..."
          kubectl get events --namespace=webapps --sort-by='.lastTimestamp' --kubeconfig=$PWD/kubeconfig.yaml | tail -15

      - name: Debug on Failure
        if: failure()
        run: |
          echo "Deployment failed. Gathering debug information..."
          kubectl describe job photovault-api --namespace=webapps --kubeconfig=$PWD/kubeconfig.yaml
          kubectl describe pods -l app=photovault-api --namespace=webapps --kubeconfig=$PWD/kubeconfig.yaml
          kubectl logs -l app=photovault-api --namespace=webapps --kubeconfig=$PWD/kubeconfig.yaml --tail=50