
name: Build and Deploy API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "IMAGE_NAME=ghcr.io/ekskog/photovault-api" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u $GITHUB_ACTOR --password-stdin <<< "${{ secrets.EK_GITHUB_PAT }}"

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
          echo "Resolved IMAGE_TAG: $IMAGE_TAG"
          docker buildx build --platform linux/amd64 -t $IMAGE_TAG --push .
      
      - name: Set Up KUBECONFIG
        run: |
          echo "${{ secrets.KUBECONFIG_FILE_CONTENT }}" > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          echo "KUBECONFIG set to $KUBECONFIG"
                    
      - name: Deploy to Kubernetes
        run: |
          IMAGE_TAG=${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
          echo "Resolved IMAGE_TAG: $IMAGE_TAG"
          kubectl set image deployment/photovault-api photovault-api=$IMAGE_TAG --namespace=webapps --kubeconfig=$PWD/kubeconfig.yaml
          kubectl rollout restart deployment/photovault-api --namespace=webapps --kubeconfig=$PWD/kubeconfig.yaml